### ISSUE TITLE
Brainstorm para indicações de ideias em projetos de software

### ISSUE THREAD

**Issue by radamesp7** [radamesp7/AbexII_G14_2024#1]
O brainstorming se aplica a disciplina de aprendizado baseado em experiências, onde os alunos em grupos indicam o que pode ser uma ideia de problema que possa ser solucionado com o desenvolvimento de um aplicativo de software e que tem uma finalidade prática. O brainstoriming deve gerar ideias entre os membros do grupo e precisa que se use como base o github para que possam trabalhar como grupo de trabalho e registrar as ideias conforme forem gerando as mesmas.

Lista de Ideias:

**Comment by vitorbcaldas** [comment]
1- Uma interface bancaria sem muitas funcionalidades, com o objetivo de mostrar o saldo e poder usar esse saldo como base para ser convertido em mais de 150 moedas e poder analisar quanto dinheiro você tem em alguma moeda de outro país

**Comment by lucasklauck06** [comment]
2- uma "calculadora que transforma o salario bruto para salario liquido para empresas que realizam o pagamento para os funcionários"

**Comment by vitorbcaldas** [comment]
3- aplicativo de reciclagem ou sustentabilidade, um aplicativo onde tenha um mapa e dentro desse mapa possuem lixeiras próximas, indicando o tipo de lixo que pode ser jogado ali, pessoas podem adicionar novos pontes de lixeiras, muitas vezes não sabemos onde descartar certos tipos de materiais, nem se possuem lixeiras próximas

**Comment by vitorbcaldas** [comment]
4- app de lembrete, você coloca tarefas que precisa fazer, pode adicionar descrição da tarefa e ele vai lembrar você

**Comment by lucasklauck06** [comment]
5- App de rotina alimentar, a medida que você irá fazendo suas refeições você adiciona no aplicativo o alimento com ou sem o peso que você consumiu naquela refeição. No final do dia vc tem um overview de como foi sua rotina alimentar e o app vai estimular o usuário a sempre se alimentar cada vez melhor e a conforme o resultado do usuario podera enviar uma notificacao "liberando uma refeicao mais prazerosa, tipo fast food ". Podemos implementar um marcador de peso (em jejum ou não) e outras features

**Comment by franzzen6590** [comment]
6- Um app que conecte profissionais autônomos (pedreiros, eletricistas, etc.) com clientes, facilitando a contratação de serviços.

**Comment by franzzen6590** [comment]
7- Um software que possibilita um Planejamento financeiro Simulando cenários futuros e criando planos de aposentadoria.

**Comment by arturzauno** [comment]
8 - Desenvolver um app de realidade aumentada que estabeleça uma conexão do mundo real para o virtual

**Comment by arturzauno** [comment]
9- App para aprender novos idiomas com diversos exercícios e jogos divertidos.

**Comment by arturzauno** [comment]
10- App para armazenar e gerenciar as suas senhas com segurança.

**Comment by franzzen6590** [comment]
11- App  para Comparação de produtos, redução de lixo e incentivo à reciclagem.

**Comment by lucasklauck06** [comment]
12- app que calcula quanto kwh sua casa gasta com os seus eletrodomesticos
